version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: daywiseuser
      POSTGRES_PASSWORD: daywisepassword
      POSTGRES_DB: daywisedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
